local deployment configuration

diff --git a/scripts/down b/scripts/down
--- a/scripts/down
+++ b/scripts/down
@@ -6,28 +6,30 @@ echo "Checking dependencies..."
 echo "Checking kubectl..."
 if ! command -v kubectl &> /dev/null
 then
-	echo "You must have Kubernetes installed!"
-	exit 1
+  echo "You must have Kubernetes installed!"
+  exit 1
 fi
 echo "OK"
 
 ## Retrieve the arguments
-while getopts r:h flag
+while getopts r:l:h flag
 do
-	case "${flag}" in
-		r) remove=${OPTARG};;
-		h) help="true";;
-		*) exit 1;;
-	esac
+  case "${flag}" in
+    r) remove=${OPTARG};;
+    l) nodeName=${OPTARG};;
+    h) help="true";;
+    *) exit 1;;
+  esac
 done
 
 ## Print help
 if [ "${remove}" != "false" ] && [ "${remove}" != "true" ] || [ "$help" == "true" ]
 then
-	echo "usage: $0 [OPTIONS]"
-	echo "  -h: shows the script help (this message)"
-	echo "	-r: true if it should remove the volumes (won't erase any data), false if it should not."
-	exit 1
+  echo "usage: $0 [OPTIONS]"
+  echo "  -h: shows the script help (this message)"
+  echo "  -r: true if it should remove the volumes (won't erase any data), false if it should not."
+  echo "  -l: Name of the Worker Node whose labels required by the volumes are to be removed"
+  exit 1
 fi
 
 # When we run only delete --all all, it can kill the pods first, not the deployments nor
@@ -40,7 +42,14 @@ kubectl delete --all all -n dojot
 
 if [ "${remove}" == "true" ]
 then
-	echo "Removing volumes"
-	kubectl delete --all pvc --all-namespaces
-	kubectl delete --all pv,sc
+  echo "Removing volumes"
+  kubectl delete --all pvc --all-namespaces
+  kubectl delete --all pv,sc
+
+  ## removes labels from worker node
+  if [ -n "${nodeName+true}" ] ; then
+    echo "labeling worker node..."
+    kubectl label nodes "${nodeName}" dojot.components/group-
+  fi
+
 fi
